'use strict';
// AUTO-GENERATED by scripts/build_muscle_map.js from Lyfta v1.528 (com.lyfta.util.helpers.Muscle).
// Editor beware: regenerate with `node scripts/build_muscle_map.js [path-to-decompiled-apk]`.
// Each entry: { name, muscle_id: <Lyfta muscle record id>, male: [{file,front}], female: [{file,front}] }.
// `front` === true means the asset is a FRONT body view, false === BACK view.

const BY_ID = [
 {
  "name": "STERNOCLEIDOMASTOID",
  "muscle_id": 34,
  "male": [],
  "female": [
   {
    "file": "front_neck_female",
    "front": true
   }
  ]
 },
 {
  "name": "PECTORALIS_MAJOR_STERNAL_HEAD",
  "muscle_id": 25,
  "male": [
   {
    "file": "front_chest",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_chest_female",
    "front": true
   }
  ]
 },
 {
  "name": "PECTORALIS_MAJOR_CLAVICULAR_HEAD",
  "muscle_id": 24,
  "male": [
   {
    "file": "front_chest_clavicular_head",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_chest_clavicular_head_female",
    "front": true
   }
  ]
 },
 {
  "name": "DELTOID_ANTERIOR",
  "muscle_id": 8,
  "male": [
   {
    "file": "front_deltoid_anterior",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_deltoid_anterior_female",
    "front": true
   }
  ]
 },
 {
  "name": "DELTOID_LATERAL",
  "muscle_id": 9,
  "male": [
   {
    "file": "front_deltoid_lateral",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_deltoid_lateral_female",
    "front": true
   }
  ]
 },
 {
  "name": "BRACHIORADIALIS",
  "muscle_id": 6,
  "male": [
   {
    "file": "front_brachioradialis",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_brachioradialis_female",
    "front": true
   }
  ]
 },
 {
  "name": "RECTUS_ABDOMINIS",
  "muscle_id": 28,
  "male": [
   {
    "file": "front_rectus_abdominis",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_rectus_abdominis_female",
    "front": true
   }
  ]
 },
 {
  "name": "SARTORIUS",
  "muscle_id": 29,
  "male": [
   {
    "file": "front_sartorius",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_sartorius_female",
    "front": true
   }
  ]
 },
 {
  "name": "SERRATUS_ANTERIOR",
  "muscle_id": 31,
  "male": [
   {
    "file": "front_serratus_anterior",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_serratus_anterior_female",
    "front": true
   }
  ]
 },
 {
  "name": "PECTINEOUS",
  "muscle_id": 23,
  "male": [
   {
    "file": "front_hip_adductors",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_hip_adductors_female",
    "front": true
   }
  ]
 },
 {
  "name": "TRANSVERSE_ABDOMINUS",
  "muscle_id": 40,
  "male": [],
  "female": []
 },
 {
  "name": "TENSOR_FASCIAE_LATAE",
  "muscle_id": 36,
  "male": [
   {
    "file": "front_tensor_fasciae_femoris",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_tensor_fasciae_latae_female",
    "front": true
   },
   {
    "file": "front_tensor_fasciae_femoris_female",
    "front": true
   }
  ]
 },
 {
  "name": "ILIOPSOAS",
  "muscle_id": 18,
  "male": [
   {
    "file": "front_iliopsoas",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_iliopsoas_female",
    "front": true
   }
  ]
 },
 {
  "name": "WRIST_EXTENSORS",
  "muscle_id": 45,
  "male": [
   {
    "file": "front_wrist_extensors",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_wris_extensors_female",
    "front": true
   },
   {
    "file": "front_wrist_extensors_female",
    "front": true
   }
  ]
 },
 {
  "name": "WRIST_FLEXORS",
  "muscle_id": 46,
  "male": [],
  "female": [
   {
    "file": "back_wrist_flexors_female",
    "front": false
   }
  ]
 },
 {
  "name": "DELTOID_POSTERIOR",
  "muscle_id": 10,
  "male": [
   {
    "file": "back_deltoids",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_deltoid_female",
    "front": false
   },
   {
    "file": "back_deltoids_female",
    "front": false
   }
  ]
 },
 {
  "name": "TRAPEZIUS_LOWER_FIBERS",
  "muscle_id": 41,
  "male": [
   {
    "file": "back_lower_trapezius",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_trapezius_female",
    "front": false
   },
   {
    "file": "back_lower_trapezius_female",
    "front": false
   }
  ]
 },
 {
  "name": "TRAPEZIUS_UPPER_FIBERS",
  "muscle_id": 43,
  "male": [
   {
    "file": "front_trapezius",
    "front": true
   },
   {
    "file": "back_upper_trapezius",
    "front": false
   }
  ],
  "female": [
   {
    "file": "front_trapezius_female",
    "front": true
   },
   {
    "file": "back_upper_trapezius_female",
    "front": false
   }
  ]
 },
 {
  "name": "TRAPEZIUS_MIDDLE_FIBERS",
  "muscle_id": 42,
  "male": [
   {
    "file": "back_middle_trapezius",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_middle_trapezius_female",
    "front": false
   }
  ]
 },
 {
  "name": "INFRASPINATUS",
  "muscle_id": 19,
  "male": [
   {
    "file": "back_infraspinatus",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_infraspinatus_female",
    "front": false
   }
  ]
 },
 {
  "name": "TERES_MAJOR",
  "muscle_id": 37,
  "male": [
   {
    "file": "back_teres_major",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_teres_major_female",
    "front": false
   }
  ]
 },
 {
  "name": "TERES_MINOR",
  "muscle_id": 38,
  "male": [
   {
    "file": "back_teres_minor",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_teres_minor_female",
    "front": false
   }
  ]
 },
 {
  "name": "LATISSIMUS_DORSI",
  "muscle_id": 20,
  "male": [
   {
    "file": "back_latissimus_dorsi",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_latissimus_dorsi_female",
    "front": false
   }
  ]
 },
 {
  "name": "ERECTOR_SPINAE",
  "muscle_id": 11,
  "male": [
   {
    "file": "back_erector_spinae",
    "front": false
   },
   {
    "file": "back_erector_spinae_feamale",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_erector_spinae_female",
    "front": false
   },
   {
    "file": "back_erector_spinae_feamale_female",
    "front": false
   }
  ]
 },
 {
  "name": "ADDUCTOR_LONGUS",
  "muscle_id": 2,
  "male": [],
  "female": []
 },
 {
  "name": "ADDUCTOR_MAGNUS",
  "muscle_id": 3,
  "male": [
   {
    "file": "back_hip_adductors",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_hip_adductors_female",
    "front": false
   }
  ]
 },
 {
  "name": "GLUTEUS_MAXIMUS",
  "muscle_id": 13,
  "male": [
   {
    "file": "back_gluteus_maximus",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_gluteus_maximus_female",
    "front": false
   }
  ]
 },
 {
  "name": "GLUTEUS_MEDIUS",
  "muscle_id": 14,
  "male": [
   {
    "file": "back_gluteus_medius",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_gluteus_medius_female",
    "front": false
   }
  ]
 },
 {
  "name": "HAMSTRINGS",
  "muscle_id": 17,
  "male": [
   {
    "file": "back_hamstrings",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_hamstrings_female",
    "front": false
   }
  ]
 },
 {
  "name": "GRACILIS",
  "muscle_id": 16,
  "male": [],
  "female": []
 },
 {
  "name": "LEVATOR_SCAPULAE",
  "muscle_id": 21,
  "male": [
   {
    "file": "back_neck",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_neck_female",
    "front": false
   }
  ]
 },
 {
  "name": "POPLITEUS",
  "muscle_id": 26,
  "male": [
   {
    "file": "back_popliteus",
    "front": false
   }
  ],
  "female": [
   {
    "file": "back_popliteus_female",
    "front": false
   }
  ]
 },
 {
  "name": "SPLENIUS",
  "muscle_id": 33,
  "male": [],
  "female": []
 },
 {
  "name": "TRICEPS_BRACHII",
  "muscle_id": 44,
  "male": [
   {
    "file": "back_triceps",
    "front": false
   },
   {
    "file": "front_triceps",
    "front": true
   }
  ],
  "female": [
   {
    "file": "back_triceps_female",
    "front": false
   },
   {
    "file": "front_triceps_female",
    "front": true
   }
  ]
 },
 {
  "name": "BICEPS_BRACHII",
  "muscle_id": 4,
  "male": [
   {
    "file": "front_biceps",
    "front": true
   },
   {
    "file": "back_biceps",
    "front": false
   }
  ],
  "female": [
   {
    "file": "front_biceps_female",
    "front": true
   },
   {
    "file": "back_biceps_female",
    "front": false
   }
  ]
 },
 {
  "name": "BRACHIALIS",
  "muscle_id": 5,
  "male": [
   {
    "file": "front_brachialis",
    "front": true
   },
   {
    "file": "back_brachialis",
    "front": false
   }
  ],
  "female": [
   {
    "file": "front_brachialis_female",
    "front": true
   },
   {
    "file": "back_brachialis_female",
    "front": false
   }
  ]
 },
 {
  "name": "OBLIQUES",
  "muscle_id": 22,
  "male": [
   {
    "file": "front_oliques",
    "front": true
   },
   {
    "file": "back_obliques",
    "front": false
   }
  ],
  "female": [
   {
    "file": "front_obliques_female",
    "front": true
   },
   {
    "file": "back_obliques_female",
    "front": false
   },
   {
    "file": "front_oliques_female",
    "front": true
   }
  ]
 },
 {
  "name": "QUADRICEPS",
  "muscle_id": 27,
  "male": [
   {
    "file": "front_quadriceps",
    "front": true
   },
   {
    "file": "back_quadriceps",
    "front": false
   }
  ],
  "female": [
   {
    "file": "front_quadriceps_female",
    "front": true
   },
   {
    "file": "back_quadriceps_female",
    "front": false
   }
  ]
 },
 {
  "name": "GASTROCNEMIUS",
  "muscle_id": 12,
  "male": [
   {
    "file": "back_gastrocnemius",
    "front": false
   },
   {
    "file": "front_gastrocnemius",
    "front": true
   }
  ],
  "female": [
   {
    "file": "back_gastrocnemius_female",
    "front": false
   },
   {
    "file": "front_gastrocnemius_female",
    "front": true
   }
  ]
 },
 {
  "name": "TIBIALIS_ANTERIOR",
  "muscle_id": 39,
  "male": [
   {
    "file": "front_tibias",
    "front": true
   }
  ],
  "female": [
   {
    "file": "front_tibias_female",
    "front": true
   }
  ]
 },
 {
  "name": "SOLEUS",
  "muscle_id": 32,
  "male": [
   {
    "file": "back_soleus",
    "front": false
   },
   {
    "file": "front_soleus",
    "front": true
   }
  ],
  "female": [
   {
    "file": "back_soleus_female",
    "front": false
   },
   {
    "file": "front_soleus_female",
    "front": true
   }
  ]
 },
 {
  "name": "GLUTEUS_MINIMUS",
  "muscle_id": 15,
  "male": [],
  "female": []
 },
 {
  "name": "DEEP_HIP_EXTERNAL_ROTATORS",
  "muscle_id": 7,
  "male": [],
  "female": []
 },
 {
  "name": "SERRATUS_ANTE",
  "muscle_id": 30,
  "male": [],
  "female": []
 },
 {
  "name": "SUBSCAPULARIS",
  "muscle_id": 35,
  "male": [],
  "female": []
 }
];

function byId(id) {
  return BY_ID.find((x) => String(x.muscle_id) === String(id)) || null;
}
function muscleById(id, gender) {
  const m = byId(id);
  if (!m) return null;
  const set = (gender === 'male' ? m.male : m.female) || [];
  return set.map((d) => ({ file: d.file, front: !!d.front }));
}
module.exports = { MUSCLE_BY_ID: BY_ID, muscleById, byId };
