#!/usr/bin/env node
'use strict';
// Reproducibly extract the Lyfta Muscle enum -> {id, male drawables, female drawables} mapping
// from a decompiled APK and write src/image/muscles.js.
// Usage: scripts/build_muscle_map.js [path-to-decompiled-apk]
//   default apk path: "../Lyfta v1.528 78 (Premium)"
const fs = require('node:fs');
const path = require('node:path');


const APK = process.argv[2] || path.join(__dirname, '..', '..', 'Lyfta v1.528 78 (Premium)');
const MUSCLE_SMALI = path.join(APK, 'smali_classes3/com/lyfta/util/helpers/Muscle.smali');
const PUBLIC_XML = path.join(APK, 'res/values/public.xml');
const OUT = path.join(__dirname, '..', 'src/image/muscles.js');

if (!fs.existsSync(MUSCLE_SMALI)) throw new Error(`Muscle.smali not found at ${MUSCLE_SMALI}`);
if (!fs.existsSync(PUBLIC_XML)) throw new Error(`public.xml not found at ${PUBLIC_XML}`);

// id (0x...) -> drawable resource name
const id2name = {};
const pubRe = /<public type="drawable" name="([a-z0-9_]+)" id="(0x[0-9a-f]+)"\s*\/>/g;
for (let m; (m = pubRe.exec(fs.readFileSync(PUBLIC_XML, 'utf8')));) id2name[m[2]] = m[1];

const txt = fs.readFileSync(MUSCLE_SMALI, 'utf8');

// Each enum constant: <init block> followed by sput-object Muscle->NAME
const defRe = /sput-object v\d+, Lcom\/lyfta\/util\/helpers\/Muscle;->(\w+):Lcom\/lyfta\/util\/helpers\/Muscle;/g;
const matches = [...txt.matchAll(defRe)];
const order = matches.map((mt, i) => ({
  name: mt[1],
  body: txt.slice(i > 0 ? matches[i - 1].index + matches[i - 1][0].length : 0, mt.index),
}));

// Drawables feeding Lwa/k;-><init>(Object,Object). The front/back flag is loaded ONCE at <clinit>
// top (v7=TRUE/front, v2=FALSE/back) and reused, so we cannot rely on a per-pair sget-object.
// Instead, the drawable resource NAME already encodes the view: front_* / back_*, and gender via _female suffix.
const drawableIdRe = /const v(\d+), (0x7f080[0-9a-fA-F]{3})\s*\n\s*invoke-static \{v\1\}, Ljava\/lang\/Integer;->valueOf\(I\)Ljava\/lang\/Integer;\s*\n\s*move-result-object v\d+\s*\n\s*invoke-direct \{[^}]*\}, Lwa\/k;-><init>\(Ljava\/lang\/Object;Ljava\/lang\/Object;\)V/g;

function drawablesOf(body) {
  const out = [];
  for (let m; (m = drawableIdRe.exec(body));) {
    const name = id2name[m[2]];
    if (!name) continue;
    const front = name.startsWith('front_');
    const female = name.endsWith('_female');
    out.push({ file: name, front, female });
  }
  // Dedupe by file preserving order
  const seen = new Set(); const dedup = [];
  for (const d of out) if (!seen.has(d.file)) { seen.add(d.file); dedup.push(d); }
  return dedup;
}

// muscleId register: the <init>(String;IIIL...;L...;)V signature occupies range {vA..vA+6}.
// arg index 3 (0=this,1=name,2=ordinal,3=muscleId,4=stringRes,5=male,6=female) -> muscleId reg = vA+3.
function muscleIdOf(body) {
  const m = body.match(/invoke-direct(?:\/range)? \{v(\d+) \.\. v(\d+)\}, Lcom\/lyfta\/util\/helpers\/Muscle;-><init>\(Ljava\/lang\/String;IIILjava\/util\/List;Ljava\/util\/List;\)V/)
    || body.match(/invoke-direct \{v(\d+), v(\d+), v(\d+), v(\d+), v(\d+), v(\d+), v(\d+)\}, Lcom\/lyfta\/util\/helpers\/Muscle;-><init>\(Ljava\/lang\/String;IIILjava\/util\/List;Ljava\/util\/List;\)V/);
  let midReg;
  if (m) {
    // range form: {vA .. vB}; this=vA, muscleId=vA+3
    if (m[2] && !m[4]) midReg = parseInt(m[1], 10) + 3;
    else midReg = parseInt(m[4], 10); // explicit list form: this=v1,name=v2,ordinal=v3,muscleId=v4,...
  }
  if (midReg == null) return null;
  // Find the most recent const to that register in the block
  const re = new RegExp(`const(?:\\/4|\\/16)? v${midReg}, (0x[0-9a-fA-F]+|-?\\d+)`, 'g');
  let val = null;
  for (let mm; (mm = re.exec(body));) val = mm[1];
  if (val == null) return null;
  return val.startsWith('0x') ? parseInt(val.slice(2), 16) : parseInt(val, 10);
}

const muscles = [];
for (const { name, body } of order) {
  const drawables = drawablesOf(body);
  const male = drawables.filter((d) => !d.female).map(({ file, front }) => ({ file, front }));
  const female = drawables.filter((d) => d.female).map(({ file, front }) => ({ file, front }));
  // For male drawables with no female sibling, attempt a female sibling name (some Lyfta assets
  // have typos or reuse the male asset). Appended so the card code can fall back gracefully.
  for (const d of male) {
    const fem = d.file + '_female';
    if (!female.some((f) => f.file === fem)) female.push({ file: fem, front: d.front });
  }
  const muscle_id = muscleIdOf(body);
  muscles.push({ name, muscle_id, male, female });
}

// Some muscles had no drawables in the smali natively (GLUTEUS_MINIMUS, DEEP_HIP_EXTERNAL_ROTATORS, SERRATUS_ANTE, SUBSCAPULARIS, SPLENIUS, GRACILIS, ADDUCTOR_LONGUS, TRANSVERSE_ABDOMINUS). Keep them with empty lists.
const header = `// AUTO-GENERATED by scripts/build_muscle_map.js from Lyfta v1.528 (com.lyfta.util.helpers.Muscle).
// Editor beware: regenerate with \`node scripts/build_muscle_map.js [path-to-decompiled-apk]\`.
// Each entry: { name, muscle_id: <Lyfta muscle record id>, male: [{file,front}], female: [{file,front}] }.
// \`front\` === true means the asset is a FRONT body view, false === BACK view.

const BY_ID = ` + JSON.stringify(muscles, null, 1) + `;

function byId(id) {
  return BY_ID.find((x) => String(x.muscle_id) === String(id)) || null;
}
function muscleById(id, gender) {
  const m = byId(id);
  if (!m) return null;
  const set = (gender === 'male' ? m.male : m.female) || [];
  return set.map((d) => ({ file: d.file, front: !!d.front }));
}
module.exports = { MUSCLE_BY_ID: BY_ID, muscleById, byId };
`;

fs.mkdirSync(path.dirname(OUT), { recursive: true });
fs.writeFileSync(OUT, `/* eslint-disable */\n'use strict';\n` + header);
console.log(`wrote ${OUT} (muscles=${muscles.length})`);